name = "LowLevelFEM"
uuid = "6171b9fb-adbf-4751-adb9-5faded75de07"
authors = ["Balázs Pere"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
