name: CompatHelper

on:
  schedule:
    - cron: '00 00 * * *'
  workflow_dispatch:

jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1'
      
      - name: Install dependencies
        run: |
          julia --project=@. -e 'using Pkg; Pkg.add("CompatHelper")'
      
      - name: Run CompatHelper
        env:
          GITHUB_TOKEN: ${{ secrets.COMPATHELPER_TOKEN }}
          COMPATHELPER_PRIV: ""
        run: |
          julia --project=@. -e 'using CompatHelper; CompatHelper.main(compat_helper_priv=nothing)'
