name: Build PDF Documentation

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.10'

      - name: Install LaTeX (TeX Live)
        run: sudo apt-get update && sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra texlive-xetex

      - name: Install Julia dependencies
        run: julia --project=docs -e 'using Pkg; Pkg.instantiate()'

      - name: Build LaTeX docs
        run: julia --project=docs docs/make.jl --format latex

      - name: Compile PDF from LaTeX
        run: |
          cd docs/build/latex
          pdflatex LowLevelFEM.tex
          pdflatex LowLevelFEM.tex  # kétszer a hivatkozások miatt

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-pdf
          path: docs/build/latex/LowLevelFEM.pdf